author: author # 作者
description: 
keyword: Windows, Android
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
#  Projects: /project/
 Links: /links/
 About: /about/
 

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment: disqus

# gitment config
gitment_owner: 
gitment_repo: 
gitment_oauth_id: 
gitment_oauth_secret: 

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: 
  description: "description"
  weibo_username: 
  twitter_username: 
  github_username: 
  telegram_username: 
  zhihu_username: 
  douban_username: 
  linkedin_username:

# MathJax Support
mathjax:s
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
